### ISSUE TITLE
Trying to upgrade from git 1.7 to 2

### ISSUE THREAD

**Issue by snorland** [githubteacher/intermediate-may#17]
trying to upgrade has been a serious headache.  I'm missed half the discussion and have not succeeded.

**Comment by githubteacher** [comment]
I'm sorry you are having troubles.  We are recording this session so you will be able to review.

Are you on Windows, Mac or Linux?

**Comment by snorland** [comment]
Mac.  I think this issue has do you with jumping a major version: 1 to 2.  Thanks, but I guess this issue is just a gripe.  I'm not going to continue trying and fall further behind.

**Comment by githubstudent** [comment]
@snorland Sorry to hear about your troubles. Please see the [Git website](https://git-scm.com); hopefully some of the documentation there can help.

We highly recommend upgrading, if only to to fix a [major security bug](https://github.com/blog/1938-git-client-vulnerability-announced) that got fixed in newer versions.

**Comment by snorland** [comment]
FYI: the version difference didn't causing any problems for todays class.  All commands ran equivalently to Cynthia's examples.  Great class.  Thanks!
